import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class ParseXmlString {
    public static void main(String[] args) {
        japan();
//        Scanner sc = new Scanner(System.in);
//        List<String> origin = new ArrayList<>();
//        List<String> trans = new ArrayList<>();
//        while (sc.hasNext()) {
//            String line = sc.nextLine();
//            if (line.equals("q")) break;
//            if (line.trim().equals("") || line.trim().startsWith("<")) {
//                origin.add(line);
//            } else {
//                trans.add(line);
//            }
//        }
//        int tranIndex = 0;
//        for (int i = 0; i < origin.size(); i++) {
//            String line = origin.get(i);
//            if (line.trim().startsWith("<string name")) {
//                int start = line.indexOf('>') + 1;
//                int end = line.indexOf("</");
//                if (!line.substring(start, end).equals(trans.get(tranIndex))) {
////                    System.out.println(tranIndex + " " + line.substring(start, end) + " xxx--- " + trans.get(tranIndex));
//                    String tran = line.substring(0, start) + trans.get(tranIndex) + line.substring(end);
////                    System.out.println(tran);
//                    origin.set(i, tran);
//                }
//                tranIndex++;
//            }
//            System.out.println(origin.get(i));
//        }
    }

    private static final String[] enTrans = new String[] {
            "U-Dictionary",
            "We have all the words you need!",
            "Local",
            "Offline Dictionary",
            "My Words",
            "Settings",
            "Copy",
            "Select the word list for lock screen",
            "Automatically Translate",
            "Clear Recent History",
            "Clear all the search history below the search box.",
            "Feedback",
            "Rate It",
            "Satisfaction Survey",
            "Report a Problem",
            "Others",
            "About",
            "New",
            "Share with Friends",
            "Display Language",
            "Undo",
            "You have downloaded the offline successfully. Tell your friends",
            "Share Now",
            "No, thanks",
            "No data",
            "Update has failed.",
            "Daily Highlights",
            "Articles",
            "Quotes for Today",
            "Fail to load. Click to try again.",
            "Share",
            "Share to",
            "Listen to the sentence",
            "Slide to view more",
            "Loading…",
            "Words, phrases or sentences",
            "Definition",
            "No Basic Result",
            "Do you want to search: ",
            "Get more online results",
            "More definitions",
            "Network not available.",
            "Delete",
            "Clear search history?",
            "Clear all history",
            "Not now",
            "Sure",
            "Yes",
            "No",
            "Loading the pronunciation…",
            "Failed to get the pronunciation. Please try again later.",
            "Do you like our app?",
            "If you enjoy using U-Dictionary, would you mind taking a moment to rate it? Thanks!",
            "Yes! Rate it now",
            "No! Report a problem",
            "Your suggestions help U-Dictionary do better. Tell us your feedback!",
            "Why not show us some love with a nice comment on Google Play?",
            "Sorry, we can\\'t find Google Play on your phone.",
            "Remind me later",
            "Try Now!",
            "Language",
            "Edit",
            "Select all",
            "Create New Folder",
            "Do you tend to recommend U-Dictionary to your friends?",
            "Suggestions from you help us make U-Dictionary better!",
            "You will receive notifications about Today\\'s Word, Today\\'s Sentence, and interesting promotions.",
            "You may miss important alerts and updates.",
            "Notifications on",
            "Notifications off",
            "It\\'s empty. Tap the star next to a translation to save it here.",
            "Refresh",
            "Type:",
            "Content: (with 5 words or more)",
            "OK",
            "Upgrade",
            "Search history cleared.",
            "Input something",
            "Translation copied. Paste to enter it.",
            "No result to paste.",
            "Sorry, we can\\'t find the app on your phone.",
            "Added to My Words!",
            "Removed from My Words!",
            "Thanks!",
            "Describe it with 5 words or more.",
            "Press Back again to quit U-Dictionary.",
            "Please give us a score.",
            "Select language",
            "Start",
            "Remove the installed offline package?",
            "Remove",
            "Offline dictionary removed.",
            "Updating this offline will delete current package.",
            "Update",
            "This language is not available offline",
            "There was a problem sending the message. Please try again later.",
            "SDCard not available.",
            "Fail to create folder in SDCard",
            "Insufficient SDCard space.",
            "Download Error. Please try again later.",
            "Download canceled.",
            "Please install offline package.",
            "Click to update",
            "Do you want to save your suggest now?",
            "Save",
            "Share via",
            "include screen shot",
            "Search",
            "U Dictionary, Google Play\\'s Best Apps of 2016.",
            "The network is unavailable. We have shown the offline results.",
            "The network is unavailable and you haven\\'t download basic offline packages.",
            "The basic offline package is not supported now.",
            "Ads",
            "Next",
            "Input word to translate",
            "Download the basic offline package",
            "Collins COBUILD Advanced Dictionary",
            "Sample Sentences",
            "English Dictionary",
            "Wikipedia",
            "Machine translation result",
            "Web Definition",
            "typos",
            "Synonyms",
            "Antonyms",
            "Bilingual Sentences",
            "Picture Dictionary",
            "Cognate words",
            "Phrases",
            "Etymology",
            "You are going to speak:",
            "Please select the word you want",
            "Your phone does not support speech recognition.",
            "View",
            "Go to view my words",
            "Don\\'t show again",
            "Word for Today is %1$s, Learn its meaning…",
            "Arabic",
            "Bengali",
            "German",
            "English",
            "Spanish",
            "French",
            "Gujarati",
            "Hindi",
            "Indonesian",
            "Italian",
            "Japanese",
            "Kannada",
            "Korean",
            "Malayalam",
            "Marathi",
            "Malay",
            "Nepali",
            "Punjabi",
            "Tamil",
            "Telugu",
            "Thai",
            "Urdu",
            "Vietnamese",
            "New List",
            "Please enter a name for this list",
            "Create",
            "Rename List",
            "Rename",
            "Delete List",
            "Select List",
            "Move to",
            "Online results.",
            "Only offline results are shown. Please download offline packages first.",
            "Now copy and you will get the meaning immediately.",
            "Click the floating icon and get the meaning.",
            "Now you can look up words offline.",
            "Can\\'t find the offline file, please re-download.",
            "We have received your feedback. Thanks.",
            "Please check your search language above.",
            "Email / Phone Number:",
            "A valid email or phone number is required.",
            "This list already exists.",
            "Failed to create list.",
            "Failed to rename list.",
            "Failed to delete list.",
            "Skip",
            "Romanization",
            "Select from the following languages, you don\\'t need to manually change translation direction.",
            "Internet connection failed. Download offline packages to get translations even when you are offline.",
            "Already downloaded",
            "Available for download",
            "Notification",
            "Copy to Translate",
            "Receive the notifications about word for today or articles.",
            "Quick Translate",
            "General Notification",
            "Receive the notifications about English learning contents.",
            "Enable Copy to Translate",
            "Instant Copy to Translate",
            "Turn on \"Display Pop-up Window\" to enable Copy to Translate",
            "Translate your language to English or reverse",
            "Set U Dictionary Language",
            "Done",
            "Turn on Word Lock Screen",
            "Learn words every time you unlock screen",
            "Keep Word Lock Screen on",
            "Ensure the normal use via turning on the auto start",
            "Find U-Dictionary and switch it on",
            "Your phone doesn\\'t support offline pronunciation. Please make sure your network connection.",
            "Translate between your language and English even when you are offline.",
            "Download Offline Package",
            "Download",
            "You have downloaded offline package.",
            "Downloading offline package needs access permission.",
            "Turn on Word Lock Screen",
            "My Favorite",
            "Your Primary Language",
            "Lock",
            "Camera access required.",
            "Search Word",
            "More",
            "Enable Word Lock Screen",
            "Select Word List",
            "If you delete this list, words in this list will be moved into \"Default\"",
            "Details",
            "Edit Original Text",
            "Parallel to reference lines",
            "Retake",
            "Copied successfully",
            "AD",
            "Translate between Hindi and English",
            "BookWord",
            "Recently used",
            "All",
            "Access authorization",
            "In order to show you personalized premium content, U-Dictionary will collect your mobile ID. \nWe promise that your data will not be disclosed.",
            "Offline package is coming soon. Please be patient!",
            "Network connection failed. Please try again!",
            "Camera",
            "Dialogue",
            "Enter the text to be translated",
            "Enter or paste the text to be translated",
            "paste",
            "Exceeded the character limit",
            "Maybe you are typing:",
            "Internet connection failed",
            "Click to Refresh",
            "History",
            "Words For Today",
            "English Corner",
            "Spelling Check",
            "Writing Club",
            "Word Game",
            "Selected Articles",
            "Join",
            "Me",
            "Privacy Policy",
            "Translation failed. Please try later.",
            "Welcome to U-Dictionary",
            "Sync the words you bookmark by login",
            "Log in with Phone",
            "Log in with Google",
            "Log in with Facebook",
            "Privacy Policy",
            "By continuing, you agree to our Privacy Policy.",
            "Log Out",
            "Are you sure you want to exit?",
            "Confirm",
            "Cancel",
            "Login succeeded.",
            "Login failed.",
            "Mobile Phone Login",
            "Phone Number",
            "Captcha",
            "Enter phone number",
            "6-Digit code",
            "Send",
            "Resend",
            "Invalid mobile number",
            "Incorrect code",
            "Log In",
            "Sent successfully",
            "Click on the card to watch the video",
            "Challenge",
            "Saved to the ablum.",
            "Click to challenge",
            "Click to end",
            "Challenge again",
            "Original sound",
            "Example",
            "My sound",
            "Recording（备注：这里是名词，录音记录的意思）",
            "Rating...",
            "70 Points",
            "Completeness",
            "Fluency",
            "Pronunciation",
            "Try to challenge it.",
            "Bravo! Your pronunciation is perfect.",
            "Wow! You sound like a native speaker.",
            "Perfect! You are amazing.",
            "Super! You sound like a native speaker.",
            "Great! You can do better.",
            "Almost perfect! Try it again.",
            "Not bad! Still need to practice harder.",
            "Good! But you can do better.",
            "Not good enough! Do not be discouraged.",
            "Not good enough! Practice harder.",
            "Class Tab (India only)",
            "Display the exam course tab in the tab bar.",
            "You are going to speak:",
            "Word Lock Screen",
            "Show English words you select on lock screen",
            "Enable Word Lock Screen",
            "Show words and meanings on lock screen",
            "Select Word List",
            "Choose words you want to show",
            "Display the search box in the notification bar.",
            "Receive notifications about English learning contents.",
            "Click to change Copy to Translate settings.",
            "Clear all the search history below the search box.",
            "Copy a word or sentence in any app to get the translation.",
            "Copy and click the U button to get the translation",
            "Copy and get the translation instantly",
            "Turn on \"Permit drawing over other apps\" to enable Copy to Translate",
            "Two-way translation and automatic detection",
            "Version",
            "Target \"+\" at the English word",
            "Word",
            "Sentence",
            "Details",
            "Fold",
            "Unfold",
            "Edit Original Text",
            "Parallel to reference lines",
            "Click (img) to lock the result",
            "Click (img) to unlock the result",
            "Click (img) to translate the contents",
            "Album",
            "Retake",
            "Copied successfully",
            "To protect your privacy, we updated our privacy policy. If you want to learn more about this, please click to view. You can also access it on this page anytime.",
            "Aha Moment",
            "The end.",
            "Welcome to conversation translation",
            "Swipe up or click to change translation language",
            "Click to speek",
            "Click button to change target language",
            "Recognition failed. Please try again!",
            "Confirm to delete all records?",
    };
    private static final String[] japanTrans = new String[] {
            "U-Dictionary",
            "私たちは、ユーザーの皆様が必要とする単語を全てご用意しています！",
            "ローカル",
            "オフライン辞書",
            "私の単語帳",
            "設定",
            "コピー",
            "ロック画面に表示する単語リストを選択する",
            "自動翻訳",
            "最近の履歴を削除する",
            "検索ボックスの履歴を全て削除する",
            "フィードバック",
            "評価する",
            "満足度調査",
            "問題を報告する",
            "その他",
            "アプリについて",
            "New",
            "友達にシェアする",
            "表示言語",
            "もとに戻す",
            "オフラインダウンロードに成功しました。",
            "今すぐシェアする",
            "いいえ",
            "データがありません",
            "アップデートに失敗しました。",
            "デイリーハイライト",
            "記事",
            "一日一文",
            "ロードに失敗しました。もう一度お試しください。",
            "シェア",
            "共有先",
            "文章を再生する",
            "スライドしてもっと見る",
            "読み込み中",
            "単語、フレーズや文章",
            "定義",
            "結果がありません",
            "検索したい内容は：",
            "オンラインの検索結果をもっとみる",
            "その他の定義",
            "ネットワークを利用できませんでした",
            "削除",
            "検索履歴を削除しますか？",
            "全ての履歴を削除しました",
            "現在はできません",
            "もちろんです",
            "はい",
            "いいえ",
            "発音をロードしています",
            "発音の読み込みに失敗しました。もう一度お試しください。",
            "このアプリを気に入っていただけましたか？",
            "もしこのアプリをお楽しみいただけていたら、評価していただけませんか？",
            "はい、評価します！",
            "いいえ！問題を報告します",
            "ユーザー様のご提案によってU-Dictionaryはより良いアプリになります。フィードバックにご連絡ください！",
            "なぜGoogle Playでオススメコメントを書き込んでみませんか？",
            "申し訳ございません。デバイスのGoogle Playが見つかりませんでした。",
            "あとでする",
            "今すぐする！",
            "言語",
            "編集する",
            "全て選択する",
            "新しいフォルダーを作成",
            "あなたはU-Dictionaryを友達とシェアする傾向にありますか？",
            "皆様からのご提案がU-Dictionaryをより良いアプリにしていきます！",
            "今日の単語や文章の通知を受け取る",
            "重要な通知やアップデートを逃してしまいます",
            "通知をオンにする",
            "通知をオフにする",
            "空になりました。翻訳の隣の星をタップしてここにセーブしてください。",
            "更新",
            "タイプ：",
            "内容：(5単語以上で)",
            "OK",
            "アップグレード",
            "検索履歴を削除しました",
            "何かをインプットします",
            "翻訳をコピーしました。貼り付けて進んでください。",
            "貼り付けの結果はありません",
            "申し訳ございません。ご利用の端末にアプリが見つかりません。",
            "My単語帳に追加しました！",
            "My単語帳から移動させました！",
            "ありがとうございます！",
            "5つの単語以上で説明する",
            "戻るをもう一度押してU-Dictionaryを退出する",
            "スコアをください",
            "言語を選択する",
            "スタート",
            "インストール済みのオフラインパッケージを移動する",
            "移動",
            "オフライン辞書を移動しました",
            "オフラインでアップデートすると現在のパッケージが消えてしまいます",
            "アップデート",
            "この言語はオフラインではご利用いただけません。",
            "問題が発生しメッセージを送れませんでした。もう一度お試しください。",
            "SDカードがご利用いただけません",
            "SDカードのフォルダー作成に失敗",
            "SDカードの容量が不十分です",
            "ダウンロードエラー発生。もう一度お試しください。",
            "ダウンロードがキャンセルされました",
            "オフラインパッケージをインストールしてください",
            "クリックしてアップデート",
            "あなたの提案をセーブしますか？",
            "セーブする",
            "でシェア",
            "スクリーンショットを含める",
            "検索",
            "U DictionaryはGoogle Play2016年のベストアプリです",
            "ネットワークを利用できません。オフラインの検索結果を表示します",
            "ネットワークを利用できません。ベーシックオフラインパッケージをダウンロードしていません",
            "ベーシックオフラインパッケージは現在起動していません",
            "広告",
            "次",
            "翻訳の単語をインプットする",
            "ベーシックオフラインパッケージをダウンロードする",
            "コリンズ　コウビルド英英辞書",
            "サンプル文章",
            "英語辞書",
            "ウィキペディア",
            "機械翻訳の結果",
            "ウェブ定義",
            "タイプミス",
            "類義語",
            "反対語",
            "2か国語の文章",
            "写真辞書",
            "同源語",
            "フレーズ",
            "語源",
            "話してください：",
            "単語を選んでください",
            "ご利用の端末はスピーチを許可していません",
            "見る",
            "My単語を見る",
            "もう表示しない",
            "今日の単語は%1$s、さてどういう意味でしょう",
            "アラビア語",
            "ベンガル語",
            "ドイツ語",
            "英語",
            "スペイン語",
            "フランス語",
            "グジャラート語",
            "ヒンディー語",
            "インドネシア語",
            "イタリア語",
            "日本語",
            "カンナダ語",
            "韓国語",
            "マレーシア語",
            "マラーティー語",
            "マレー語",
            "ネパール語",
            "パンジャブ語",
            "タミル語",
            "テルグ語",
            "タイ語",
            "ウルドゥー語",
            "ベトナム語",
            "新リスト",
            "このリストの名前を入れてください",
            "作成",
            "リストの名前を変更する",
            "名前を変更",
            "リストを削除",
            "リストを選択",
            "に移動する",
            "オンラインの検索結果",
            "オフラインの結果のみが表示されています。始めにオフラインパッケージをダウンロードしてください",
            "コピーしました。すぐに意味を表示します。",
            "浮かんでいるアイコンをクリックして意味を検索",
            "オフラインでも単語をご覧いただけます。",
            "オフラインファイルが見つかりませんでした。もう一度ダウンロードしてください。",
            "フィードバックを受け取りました。ありがとうございます。",
            "上記から言語をお選びください",
            "Eメール/携帯番号",
            "有効なEメールあるいは携帯番号が必要です。",
            "このリストはすでに存在します",
            "リストの作成に失敗しました。",
            "リストの名前変更に失敗しました。",
            "リストの削除に失敗しました。",
            "スキップ",
            "ローマ字",
            "",
            "インターネット接続に失敗しました。オフラインで翻訳するためにオフラインパッケージをダウンロードしてください。",
            "ダウンロードしました",
            "ダウンロードできません",
            "通知",
            "コピーして翻訳",
            "今日の単語と記事についての通知を受け取る",
            "クイック翻訳",
            "一般的な通知",
            "英語学習コンテンツについての通知を受け取る",
            "“コピーで翻訳”できるようにする",
            "インスタントコピーで翻訳",
            "“コピーで翻訳”を利用可能にするために、ディスプレイポップアップウィンドウを起動する",
            "あなたの言語を英語あるいはその他の言語に翻訳する",
            "U Dictionaryの言語を設定",
            "完了しました",
            "ロック画面の単語表示する",
            "アンロック画面で常時単語を学習する",
            "ロック画面に単語を固定する",
            "自動スタートを常用に確定する",
            "U-Dictionaryを探して切り替える",
            "お使いの端末はオフラインで発音機能をご利用いただけません。ネットワークを確認んしてください",
            "オフラインでも選んだ言語と英語を翻訳する",
            "オフラインパッケージをダウンロードする",
            "ダウンロード",
            "オフラインパッケージをダウンロードしました",
            "オフラインパッケージのダウンロードにアクセスの許可が必要です",
            "ロック画面の単語表示をオンにする",
            "お気に入り",
            "あなたの第一言語",
            "ロック",
            "カメラへのアクセス必要です",
            "単語を検索",
            "もっと",
            "ロック画面の単語表示を利用可能にする",
            "選択した単語リスト",
            "このリストを削除すると、リスト内の単語は\"デフォルト\"に移動します",
            "詳細",
            "オリジナルテキストを編集する",
            "基準線に平行に",
            "リテイク",
            "コピーに成功しました",
            "広告",
            "ヒンディー語と英語の間で翻訳する",
            "ブックワード",
            "最近ご利用になられたもの",
            "全て",
            "アクセスを許可する",
            "",
            "オフラインパッケージはもうすぐ完成します、少々お待ちください。",
            "ネットワーク接続に失敗しました。もう一度お試しください。",
            "カメラ",
            "対話",
            "翻訳するテキストを入力する",
            "翻訳するテキストを入力もしくは貼り付けする",
            "貼り付け",
            "文字数が多すぎます",
            "あなたが検索したいのはこちらではないですか？：",
            "インターネット接続に失敗しました。",
            "クリックして更新",
            "履歴",
            "今日の単語",
            "英語コーナー",
            "スペリングチェック",
            "ライティングクラブ",
            "単語ゲーム",
            "選りすぐりの記事",
            "参加",
            "私",
            "プライバシーポリシー",
            "翻訳に失敗しました。少ししてからもう一度お試しください。",
            "U-Dictionaryへようこそ",
            "ログインでブックマークの単語を同期",
            "携帯でログイン",
            "Googleでログイン",
            "Facebookでログイン",
            "プライバシーポリシー",
            "私たちのプライバシーポリシーに同意する",
            "ログアウト",
            "本当に退出しますか？",
            "確定",
            "キャンセル",
            "ログインに成功しました",
            "ログインに失敗しました",
            "電話番号でログイン",
            "携帯番号",
            "認証コード",
            "携帯番号を入力",
            "6桁の認証コード",
            "送信",
            "再送信",
            "携帯番号が無効です",
            "認証コードが違います",
            "ログイン",
            "送信成功",
            "カードをタップしてビデオを再生する",
            "続ける",
            "アルバムに保存する",
            "クリックして挑戦",
            "クリックして終了する",
            "再挑戦する",
            "オリジナルサウンド",
            "例",
            "マイサウンド",
            "録音",
            "評価中",
            "70点",
            "完成度",
            "流暢さ",
            "発音",
            "もう一度挑戦",
            "ブラボー！完璧な発音です！",
            "わあ！ネイティブスピーカーみたい！",
            "パーフェクト！素晴らしいです！",
            "すごい！ネイティブスピーカーみたい！",
            "すごい！でももっとできるはず！",
            "ほぼパーフェクト！もう一度やってみよう！",
            "いい感じ！もっと練習してみよう！",
            "悪くない！でももっと頑張ろう！",
            "全然ダメ！もっと頑張ろう！",
            "全然ダメ！もっと練習しよう！",
            "授業欄(インド語のみ)",
            "ページにテストコースをディスプレイする",
            "なにを話しますか：",
            "ロック画面の単語表示",
            "ロック画面に選んだ英単語を表示",
            "ロック画面に単語表示できません",
            "単語とその意味をロック画面に表示する",
            "単語リストを選択",
            "表示したい単語を選ぶ",
            "通知バーに検索ボックスをディスプレイする",
            "英語学習コンテンツの通知を受け取る",
            "クリックして“コピーで翻訳”の設定を変更する",
            "検索ボックス内の検索履歴をすべて削除する",
            "他のアプリの単語や文章をコピーして翻訳する",
            "コピーしたらUボタンをクリックして翻訳する",
            "コピーして即時に翻訳する",
            "“他のアプリの上に重ねて表示する”をオンにしてコピー翻訳を利用可能にする",
            "2つの方法で翻訳し自動発見",
            "バージョン",
            "\"+\"をターゲットにして英単語に",
            "単語",
            "文章",
            "詳細",
            "閉じる",
            "開く",
            "オリジナルテキストを編集する",
            "基準線と平行に",
            "(img)をクリックして検索結果をロック",
            "(img)をクリックして検索結果をアンロック",
            "(img)をクリックして内容を翻訳",
            "アルバム",
            "リテイク",
            "コピーに成功しました",
            "皆様の個人情報保護のため、プライバシーポリシーを更新しました。いつでもクリックして詳細をご覧いただけます。",
            "ひらめきタイム",
            "検索結果はここまでです",
            "会話翻訳へようこそ！",
            "スワイプまたはクリックして翻訳言語を変更する",
            "クリックして話す",
            "ボタンをクリックして目標言語を変更する",
            "識別できませんでした。もう一度お試しください！",
            "すべての履歴を削除しますか？"
    };
    private static void japan() {
        Scanner sc = new Scanner(System.in);
        int idx = 0;
        while (sc.hasNext()) {
            String line = sc.nextLine();
            if (line.trim().startsWith("<string name")) {
                int start = line.indexOf('>') + 1;
                int end = line.indexOf("</");
                String s = line.substring(start, end);
                int findIndex = find(line.substring(start, end));
                if (findIndex >= 0) {
                    line = line.substring(0, start) + japanTrans[findIndex] + line.substring(end);
                }
//                if (line.substring(start, end).equals(enTrans[idx])) {
//                    line = line.substring(0, start) + japanTrans[idx++] + line.substring(end);
//                } else {
//                    System.out.println("---------------------");
//                    System.out.println(line.substring(start, end));
//                    System.out.println(enTrans[idx]);
//                }
            }
            System.out.println(line);
        }
    }

    private static int find(String en) {
        for (int i = 0; i < enTrans.length; i++) {
            if (en.equalsIgnoreCase(enTrans[i])) {
                return i;
            }
        }
        return -1;
    }
}
